### ISSUE TITLE
Unable to scrape all troop data

### ISSUE THREAD

**Issue by zengfung** [zengfung/ClashOfClansScraper#7]
Current bugs:

- [x] Spells are not scraped because `spell.level` is not present -- to be fixed in #6 
- [ ] Hero pets all have ID 0 -- to be fixed directly from package  (https://github.com/mathsman5133/coc.py/issues/156)
- [x] Builder troops are not scraped because code currently does not call `client.get_troop('<troop>', is_home_village = False)` -- to be fixed in #10 
- [x] Super troops data do not contain their corresponding original troop ID -- to be fixed in #6
- [x] Cooldown and duration data for super troops are not scraped -- to be fixed in #6
